eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8760/eureka/  #指定注册中心的地址。
server:
  port: 8761
spring:
  application:
    name: clintOne
management:
  security:
    #关闭安全验证，否则访问refresh端点时会提示权限不足
    enabled: false    

#  zipkin:  #链路追踪配置
#    base-url: http://localhost:9411   #zipkinServer 的地址
#  sleuth:
#    sampler:
 #     percentage: 1.0     #用来指定采样请求的百分比（默认为0.1，即10%）    